name: 1. DEV Environment Build

on:
  - push
  - workflow_dispatch

concurrency: deploy-${{'{'}}{ github.ref_name }}
  
jobs:
  build_and_deploy:
    uses: p6m-dev/github-actions/.github/workflows/build-deploy-rust-service.yaml@main
    with:
      MODE: release
      DOCKER_REGISTRY: p6m.jfrog.io
      DOCKER_IMAGE_NAME: {{ org-solution-name }}-docker/applications/${{'{'}}{ github.event.repository.name }}-server
      DOCKER_CONTEXT: "."
      DOCKERFILE: ./.platform/docker/external/Dockerfile
      CARGO_REGISTRY_ALIAS: {{ org-solution-name }}
      CARGO_PACKAGES: {{ project_name }}_core {{ project_name }}_server
    secrets:
      DOCKER_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      DOCKER_PASSWORD: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      CARGO_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}

  generate_subgraph:
    name: Generate Subgraph
    needs: build_and_deploy
    uses: p6m-dev/github-actions/.github/workflows/generate-rust-subgraph-domain-gateway.yaml@main
    with:
      APPLICATION_IMAGE: p6m.jfrog.io/${{'{'}}{ github.repository_owner }}-docker-local/applications/${{'{'}}{ github.event.repository.name }}-server@${{'{'}}{ needs.build_and_deploy.outputs.digest }}
    secrets:
      SUBGRAPH_PULL_TOKEN: ${{'{'}}{ secrets.REPOSITORY_PUSH_TOKEN }}
      REPOSITORY_PUSH_TOKEN: ${{'{'}}{ secrets.REPOSITORY_PUSH_TOKEN }}
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      PIPELINE_TRIGGER_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
